import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rawChannels = [
  {
    "id": "ch-1",
    "number": 1,
    "name": "BTV",
    "bnName": "বাংলাদেশ টেলিভিশন (বিটিভি)",
    "category": "news",
    "categoryLabel": "News Channels",
    "categoryBn": "নিউজ চ্যানেল",
    "logo": "https://raw.githubusercontent.com/ahan443/logo/refs/heads/main/btv.png",
    "streamUrl": "http://103.165.93.31:8095/btv/tracks-v1a1/mono.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "National News & Cultural Programs",
    "currentShowBn": "জাতীয় সংবাদ ও সাংস্কৃতিক অনুষ্ঠান",
    "nextShow": "Next: Super Program Showcase (2:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (2:00 PM)",
    "viewers": 1579,
    "isPopular": true
  },
  {
    "id": "ch-2",
    "number": 2,
    "name": "BTV News",
    "bnName": "বিটিভি নিউজ",
    "category": "news",
    "categoryLabel": "News Channels",
    "categoryBn": "নিউজ চ্যানেল",
    "logo": "https://raw.githubusercontent.com/ahan443/logo/refs/heads/main/btv%20news.png",
    "streamUrl": "http://103.165.93.31:8095/btv/tracks-v1a1/mono.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Hourly News Bulletin",
    "currentShowBn": "ঘণ্টাভিত্তিক সংবাদ বুলেটিন",
    "nextShow": "Next: Super Program Showcase (3:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (3:00 PM)",
    "viewers": 1758,
    "isPopular": true
  },
  {
    "id": "ch-3",
    "number": 3,
    "name": "Toffee TV",
    "bnName": "টফি টিভি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://raw.githubusercontent.com/ahan443/logo/refs/heads/main/circle-512.jpg",
    "streamUrl": "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Live Streaming & Web Series",
    "currentShowBn": "লাইভ স্ট্রিমিং ও ওয়েব সিরিজ",
    "nextShow": "Next: Super Program Showcase (4:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (4:00 PM)",
    "viewers": 1937,
    "isPopular": true
  },
  {
    "id": "ch-4",
    "number": 4,
    "name": "Bangla 1",
    "bnName": "বাংলা ১",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/R0J6rLBn/r2Pe-JQRk-KVBJNHu-A1u-ABt-MFat3ZFl-Xm4oj-Tt5SWI.png",
    "streamUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    "streamType": "video",
    "resolution": "1080p FHD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "General Entertainment",
    "currentShowBn": "সাধারণ বিনোদন",
    "nextShow": "Next: Super Program Showcase (5:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (5:00 PM)",
    "viewers": 2116,
    "isPopular": true
  },
  {
    "id": "ch-5",
    "number": 5,
    "name": "ATN Bangla",
    "bnName": "এটিএন বাংলা",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://raw.githubusercontent.com/ahan443/logo/refs/heads/main/atn%20bangla.png",
    "streamUrl": "https://tvsen5.aynaott.com/P3y2URgG7LDe/index.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Talk Show & Drama",
    "currentShowBn": "টক শো ও নাটক",
    "nextShow": "Next: Super Program Showcase (6:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (6:00 PM)",
    "viewers": 2295,
    "isPopular": true
  },
  {
    "id": "ch-6",
    "number": 6,
    "name": "ATN News",
    "bnName": "এটিএন নিউজ",
    "category": "news",
    "categoryLabel": "News Channels",
    "categoryBn": "নিউজ চ্যানেল",
    "logo": "https://i.postimg.cc/W4SwWtd3/20240822-225840.png",
    "streamUrl": "https://tvsen6.aynaott.com/da6WMXAk/index.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "24/7 Live News Coverage",
    "currentShowBn": "২৪ ঘণ্টা লাইভ সংবাদ",
    "nextShow": "Next: Super Program Showcase (7:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (7:00 PM)",
    "viewers": 2474,
    "isPopular": true
  },
  {
    "id": "ch-7",
    "number": 7,
    "name": "Boishakhi",
    "bnName": "বৈশাখী টিভি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/5NFp4xR7/20240822-225600.png",
    "streamUrl": "https://tvsen6.aynaott.com/1d3uG9VCgrR9DRtWZM57/index.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Musical Night & Natok",
    "currentShowBn": "মিউজিক্যাল নাইট ও নাটক",
    "nextShow": "Next: Super Program Showcase (8:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (8:00 PM)",
    "viewers": 2653,
    "isPopular": true
  },
  {
    "id": "ch-8",
    "number": 8,
    "name": "Ekushe TV",
    "bnName": "একুশে টিভি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/rsDjtcFp/20240822_225424.png",
    "streamUrl": "https://app24.jagobd.com.bd/c3VydmVyX8RpbEU9Mi8xNy8yMFDEEHGcfRgzQ6NTAgdEoaeFzbF92YWxIZTO0U0ezN1IzMyfvcEdsEfeDeKiNkVN3PTOmdFseWRtaW51aiPhnPTI2/ekusheytv-8-org.stream/index.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Ekusher Dupur & Drama",
    "currentShowBn": "একুশের দুপুর ও ধারাবাহিক নাটক",
    "nextShow": "Next: Super Program Showcase (9:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (9:00 PM)",
    "viewers": 2832,
    "isPopular": true
  },
  {
    "id": "ch-9",
    "number": 9,
    "name": "Channel i",
    "bnName": "চ্যানেল আই",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/W3WS3tVK/20240822-225402.png",
    "streamUrl": "https://tvsen6.aynaott.com/FNHpYvGZ7FkCE10PwTHm/index.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Hridoye Mati O Manush",
    "currentShowBn": "হৃদয়ে মাটি ও মানুষ",
    "nextShow": "Next: Super Program Showcase (10:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (10:00 PM)",
    "viewers": 3011,
    "isPopular": true
  },
  {
    "id": "ch-10",
    "number": 10,
    "name": "N TV",
    "bnName": "এনটিভি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/3rqnQyn0/20240822-225501.png",
    "streamUrl": "https://tvsen5.aynaott.com/xV4jEKf3D9zc/index.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Prime Time Mega Serial",
    "currentShowBn": "প্রাইম টাইম মেগা সিরিয়াল",
    "nextShow": "Next: Super Program Showcase (11:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (11:00 PM)",
    "viewers": 3190,
    "isPopular": true
  },
  {
    "id": "ch-11",
    "number": 11,
    "name": "RTV",
    "bnName": "আরটিভি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/fy1KcFJf/20240822_225533.png",
    "streamUrl": "https://tvsen5.aynaott.com/RtvHD/index.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Folk Live & Drama",
    "currentShowBn": "ফোক লাইভ ও মিউজিক স্টেশন",
    "nextShow": "Next: Super Program Showcase (12:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (12:00 PM)",
    "viewers": 3369,
    "isPopular": true
  },
  {
    "id": "ch-12",
    "number": 12,
    "name": "Banglavision",
    "bnName": "বাংলাভিশন",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/L83Ngf3C/banglavision.webp",
    "streamUrl": "https://tvsen5.aynaott.com/tgUzpPc9r6xw/index.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "News & Entertainment",
    "currentShowBn": "সংবাদ ও বিনোদন",
    "nextShow": "Next: Super Program Showcase (1:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (1:00 PM)",
    "viewers": 3548,
    "isPopular": true
  },
  {
    "id": "ch-13",
    "number": 13,
    "name": "Ananda TV",
    "bnName": "আনন্দ টিভি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://www.jagobd.com/wp-content/uploads/2018/04/Anandatvupdate.jpg?x95285",
    "streamUrl": "https://app24.jagobd.com.bd/c3VydmVyX8RpbEU9Mi8xNy8yMFDEEHGcfRgzQ6NTAgdEoaeFzbF92YWxIZTO0U0ezN1IzMyfvcEdsEfeDeKiNkVN3PTOmdFseWRtaW51aiPhnPTI2/anandatv.stream/index.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Cultural Program",
    "currentShowBn": "সাংস্কৃতিক অনুষ্ঠান",
    "nextShow": "Next: Super Program Showcase (2:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (2:00 PM)",
    "viewers": 3727,
    "isPopular": true
  },
  {
    "id": "ch-14",
    "number": 14,
    "name": "Somoy Tv",
    "bnName": "সময় টিভি",
    "category": "news",
    "categoryLabel": "News Channels",
    "categoryBn": "নিউজ চ্যানেল",
    "logo": "https://i.postimg.cc/QCKgdb09/20240822-230145.png",
    "streamUrl": "https://stream.ottplus.bd/live/somoy_tv_abr/index.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Live Breaking News",
    "currentShowBn": "লাইভ ব্রেকিং নিউজ",
    "nextShow": "Next: Super Program Showcase (3:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (3:00 PM)",
    "viewers": 3906,
    "isPopular": true
  },
  {
    "id": "ch-15",
    "number": 15,
    "name": "Independent",
    "bnName": "ইন্ডিপেন্ডেন্ট টিভি",
    "category": "news",
    "categoryLabel": "News Channels",
    "categoryBn": "নিউজ চ্যানেল",
    "logo": "https://i.postimg.cc/gr9VXZTM/20240822-230259.png",
    "streamUrl": "https://stream.ottplus.bd/live/independent_tv_abr/index.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Nightly News & Analysis",
    "currentShowBn": "রাতের সংবাদ ও বিশ্লেষণ",
    "nextShow": "Next: Super Program Showcase (4:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (4:00 PM)",
    "viewers": 4085,
    "isPopular": true
  },
  {
    "id": "ch-16",
    "number": 16,
    "name": "Jamuna",
    "bnName": "যমুনা টিভি",
    "category": "news",
    "categoryLabel": "News Channels",
    "categoryBn": "নিউজ চ্যানেল",
    "logo": "https://i.postimg.cc/G2V7K9fD/20240822-230750.png",
    "streamUrl": "https://tvsen6.aynaott.com/KGdZEdA7qQ43dmPkgk1j/index.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Jamuna Investigative Report",
    "currentShowBn": "যমুনা ইনভেস্টিগেটিভ রিপোর্ট",
    "nextShow": "Next: Super Program Showcase (5:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (5:00 PM)",
    "viewers": 4264,
    "isPopular": true
  },
  {
    "id": "ch-17",
    "number": 17,
    "name": "Channel 1",
    "bnName": "চ্যানেল ১",
    "category": "news",
    "categoryLabel": "News Channels",
    "categoryBn": "নিউজ চ্যানেল",
    "logo": "https://i.postimg.cc/Zqgx8hm1/20260430-184013.png",
    "streamUrl": "https://stream.ottplus.live/live/channel_1_hd_abr/index.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Live Broadcast",
    "currentShowBn": "লাইভ সম্প্রচার",
    "nextShow": "Next: Super Program Showcase (6:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (6:00 PM)",
    "viewers": 4443,
    "isPopular": false
  },
  {
    "id": "ch-18",
    "number": 18,
    "name": "Star News",
    "bnName": "স্টার নিউজ",
    "category": "news",
    "categoryLabel": "News Channels",
    "categoryBn": "নিউজ চ্যানেল",
    "logo": "https://static.wikia.nocookie.net/etv-gspn-bangla/images/4/45/Star_News_Bangladesh.png",
    "streamUrl": "https://static.jagobd.com.bd/c3VydmVyX8RpbEU9Mi8xNy8yMFDEEHGcfRgzQ6NTAgdEoaeFzbF92YWxIZTO0U0ezN1IzMyfvcEdsEfeDeKiNkVN3PTOmdFseWRtaW51aiPhnPTI2/starnewsbd.stream/playlist.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Global News Stream",
    "currentShowBn": "বিশ্ব সংবাদ প্রবাহ",
    "nextShow": "Next: Super Program Showcase (7:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (7:00 PM)",
    "viewers": 4622,
    "isPopular": false
  },
  {
    "id": "ch-19",
    "number": 19,
    "name": "Rajdhani",
    "bnName": "রাজধানী টিভি",
    "category": "news",
    "categoryLabel": "News Channels",
    "categoryBn": "নিউজ চ্যানেল",
    "logo": "https://i.postimg.cc/0QRnM89n/20240825-071012.png",
    "streamUrl": "https://stream.shariarsuvo.com/hls5/rajdhanicable.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Capital City News",
    "currentShowBn": "রাজধানীর খবর",
    "nextShow": "Next: Super Program Showcase (8:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (8:00 PM)",
    "viewers": 4801,
    "isPopular": false
  },
  {
    "id": "ch-20",
    "number": 20,
    "name": "EP TV",
    "bnName": "ইপি টিভি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/dQyBRGZR/eptv-large-1784915389231-9f42f1b48d424c8c.webp",
    "streamUrl": "https://app24.jagobd.com.bd/c3VydmVyX8RpbEU9Mi8xNy8yMFDEEHGcfRgzQ6NTAgdEoaeFzbF92YWxIZTO0U0ezN1IzMyfvcEdsEfeDeKiNkVN3PTOmdFseWRtaW51aiPhnPTI2/eptv.stream/playlist.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Entertainment Special",
    "currentShowBn": "বিনোদনমূলক অনুষ্ঠান",
    "nextShow": "Next: Super Program Showcase (9:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (9:00 PM)",
    "viewers": 4980,
    "isPopular": false
  },
  {
    "id": "ch-21",
    "number": 21,
    "name": "News 21 Bangla TV",
    "bnName": "নিউজ ২১ বাংলা",
    "category": "news",
    "categoryLabel": "News Channels",
    "categoryBn": "নিউজ চ্যানেল",
    "logo": "https://i.postimg.cc/8knh34Z5/iju-Jfmd.png",
    "streamUrl": "http://103.190.133.68:1935/news21live/live/playlist.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Live News",
    "currentShowBn": "লাইভ সংবাদ",
    "nextShow": "Next: Super Program Showcase (10:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (10:00 PM)",
    "viewers": 5159,
    "isPopular": false
  },
  {
    "id": "ch-22",
    "number": 22,
    "name": "Enter TV",
    "bnName": "এন্টার টিভি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/g06jByt1/entertv.jpg",
    "streamUrl": "https://live1.entertv.com.bd/entertv/index.fmp4.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Movie & Shows",
    "currentShowBn": "সিনেমা ও অনুষ্ঠান",
    "nextShow": "Next: Super Program Showcase (11:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (11:00 PM)",
    "viewers": 5338,
    "isPopular": false
  },
  {
    "id": "ch-23",
    "number": 23,
    "name": "Channel 24",
    "bnName": "চ্যানেল ২৪",
    "category": "news",
    "categoryLabel": "News Channels",
    "categoryBn": "নিউজ চ্যানেল",
    "logo": "https://i.postimg.cc/0ys4hMyd/20240822-230446.png",
    "streamUrl": "https://stream.ottplus.bd/live/somoy_tv_abr/index.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Live News & Debate",
    "currentShowBn": "সংবাদ ও টকশো",
    "nextShow": "Next: Super Program Showcase (12:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (12:00 PM)",
    "viewers": 5517,
    "isPopular": true
  },
  {
    "id": "ch-24",
    "number": 24,
    "name": "Ekattor HD",
    "bnName": "একাত্তর টিভি",
    "category": "news",
    "categoryLabel": "News Channels",
    "categoryBn": "নিউজ চ্যানেল",
    "logo": "https://i.postimg.cc/BnBz3S8W/20240822-230603.png",
    "streamUrl": "https://tvsen6.aynaott.com/EWDrV5QskgarZEUBb3pU/index.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Ekattor Journal",
    "currentShowBn": "একাত্তর জার্নাল",
    "nextShow": "Next: Super Program Showcase (1:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (1:00 PM)",
    "viewers": 5696,
    "isPopular": true
  },
  {
    "id": "ch-25",
    "number": 25,
    "name": "DBC News",
    "bnName": "ডিবিসি নিউজ",
    "category": "news",
    "categoryLabel": "News Channels",
    "categoryBn": "নিউজ চ্যানেল",
    "logo": "https://i.postimg.cc/hvmC5cF5/20240822_230837.png",
    "streamUrl": "https://tvsen6.aynaott.com/pF66Tkz0qFwP2aMMqHyt/index.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Rajkahini & News",
    "currentShowBn": "রাজকাহিনি ও সংবাদ",
    "nextShow": "Next: Super Program Showcase (2:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (2:00 PM)",
    "viewers": 5875,
    "isPopular": true
  },
  {
    "id": "ch-26",
    "number": 26,
    "name": "Desh TV",
    "bnName": "দেশ টিভি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/xTz0Qj3G/DESH-TV1.png",
    "streamUrl": "https://app24.jagobd.com.bd/c3VydmVyX8RpbEU9Mi8xNy8yMFDEEHGcfRgzQ6NTAgdEoaeFzbF92YWxIZTO0U0ezN1IzMyfvcEdsEfeDeKiNkVN3PTOmdFseWRtaW51aiPhnPTI2/deshtv.stream/index.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Music & Drama",
    "currentShowBn": "মিউজিক ও নাটক",
    "nextShow": "Next: Super Program Showcase (3:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (3:00 PM)",
    "viewers": 6054,
    "isPopular": false
  },
  {
    "id": "ch-27",
    "number": 27,
    "name": "SA TV",
    "bnName": "এসএ টিভি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/pd019sYq/20240822_230705.png",
    "streamUrl": "https://tvsen6.aynaott.com/rELXiuUXqbgzPb06Npom/index.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Gaane Gaane Shokal",
    "currentShowBn": "গানে গানে সকাল",
    "nextShow": "Next: Super Program Showcase (4:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (4:00 PM)",
    "viewers": 6233,
    "isPopular": false
  },
  {
    "id": "ch-28",
    "number": 28,
    "name": "News 24",
    "bnName": "নিউজ ২৪",
    "category": "news",
    "categoryLabel": "News Channels",
    "categoryBn": "নিউজ চ্যানেল",
    "logo": "https://i.postimg.cc/wThf5qQt/20240822_230921.png",
    "streamUrl": "https://tvsen6.aynaott.com/cdgr3tw6WoG7JyRnLbi0/index.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Live Bulletin",
    "currentShowBn": "লাইভ বুলেটিন",
    "nextShow": "Next: Super Program Showcase (5:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (5:00 PM)",
    "viewers": 6412,
    "isPopular": true
  },
  {
    "id": "ch-29",
    "number": 29,
    "name": "Deepto",
    "bnName": "দীপ্ত টিভি",
    "category": "drama",
    "categoryLabel": "Natok & Drama",
    "categoryBn": "নাটক",
    "logo": "https://i.postimg.cc/bYSFJHG9/20240822-230812.png",
    "streamUrl": "https://byphdgllyk.gpcdn.net/hls/deeptotv/index.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Dubbed Serial & Drama",
    "currentShowBn": "ডাবিং সিরিয়াল ও নাটক",
    "nextShow": "Next: Super Program Showcase (6:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (6:00 PM)",
    "viewers": 6591,
    "isPopular": true
  },
  {
    "id": "ch-30",
    "number": 30,
    "name": "Maasranga",
    "bnName": "মাছরাঙা টেলিভিশন",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/1R8bF1d6/20240822-230344.png",
    "streamUrl": "https://mtv.sunplex.live/MAASRANGA/index.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Ranga Shokal & Movies",
    "currentShowBn": "রাঙা সকাল ও সিনেমা",
    "nextShow": "Next: Super Program Showcase (7:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (7:00 PM)",
    "viewers": 6770,
    "isPopular": true
  },
  {
    "id": "ch-31",
    "number": 31,
    "name": "Ekhon",
    "bnName": "এখন টিভি",
    "category": "news",
    "categoryLabel": "News Channels",
    "categoryBn": "নিউজ চ্যানেল",
    "logo": "https://i.postimg.cc/1tkB62gc/20240822-231147.png",
    "streamUrl": "https://app24.jagobd.com.bd/c3VydmVyX8RpbEU9Mi8xNy8yMFDEEHGcfRgzQ6NTAgdEoaeFzbF92YWxIZTO0U0ezN1IzMyfvcEdsEfeDeKiNkVN3PTOmdFseWRtaW51aiPhnPTI2/globaltv.stream/index.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Ekhon Live News",
    "currentShowBn": "এখন লাইভ সংবাদ",
    "nextShow": "Next: Super Program Showcase (8:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (8:00 PM)",
    "viewers": 6949,
    "isPopular": false
  },
  {
    "id": "ch-32",
    "number": 32,
    "name": "Global TV",
    "bnName": "গ্লোবাল টিভি",
    "category": "news",
    "categoryLabel": "News Channels",
    "categoryBn": "নিউজ চ্যানেল",
    "logo": "https://i.postimg.cc/Xq98gLdM/20240822_231218.png",
    "streamUrl": "https://app24.jagobd.com.bd/c3VydmVyX8RpbEU9Mi8xNy8yMFDEEHGcfRgzQ6NTAgdEoaeFzbF92YWxIZTO0U0ezN1IzMyfvcEdsEfeDeKiNkVN3PTOmdFseWRtaW51aiPhnPTI2/Global-tv.stream/index.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Global News Hour",
    "currentShowBn": "গ্লোবাল নিউজ আওয়ার",
    "nextShow": "Next: Super Program Showcase (9:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (9:00 PM)",
    "viewers": 7128,
    "isPopular": false
  },
  {
    "id": "ch-33",
    "number": 33,
    "name": "Channel S",
    "bnName": "চ্যানেল এস",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/L6MvsdFm/20240822-231309.png",
    "streamUrl": "https://app24.jagobd.com.bd/c3VydmVyX8RpbEU9Mi8xNy8yMFDEEHGcfRgzQ6NTAgdEoaeFzbF92YWxIZTO0U0ezN1IzMyfvcEdsEfeDeKiNkVN3PTOmdFseWRtaW51aiPhnPTI2/channels.stream/index.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "UK & Bangla News",
    "currentShowBn": "ইউকে ও বাংলা নিউজ",
    "nextShow": "Next: Super Program Showcase (10:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (10:00 PM)",
    "viewers": 7307,
    "isPopular": false
  },
  {
    "id": "ch-34",
    "number": 34,
    "name": "Mohona Tv",
    "bnName": "মোহনা টিভি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/PxxzBhDM/20240822-230101.png",
    "streamUrl": "https://tvsen5.aynaott.com/tgUzpPc9r6xw/index.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Cultural Live",
    "currentShowBn": "সাংস্কৃতিক অনুষ্ঠান",
    "nextShow": "Next: Super Program Showcase (11:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (11:00 PM)",
    "viewers": 7486,
    "isPopular": false
  },
  {
    "id": "ch-35",
    "number": 35,
    "name": "Nagorik",
    "bnName": "নাগরিক টিভি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/Z54fVGww/20240822_230947.png",
    "streamUrl": "https://flussonic.defineatoz.com/backup/tracks-v1a1/mono.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Comedy & Drama",
    "currentShowBn": "কমেডি ও নাটক",
    "nextShow": "Next: Super Program Showcase (12:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (12:00 PM)",
    "viewers": 7665,
    "isPopular": true
  },
  {
    "id": "ch-36",
    "number": 36,
    "name": "Green TV",
    "bnName": "গ্রিন টিভি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/ry4QcVbh/20240822-231240.png",
    "streamUrl": "https://app24.jagobd.com.bd/c3VydmVyX8RpbEU9Mi8xNy8yMFDEEHGcfRgzQ6NTAgdEoaeFzbF92YWxIZTO0U0ezN1IzMyfvcEdsEfeDeKiNkVN3PTOmdFseWRtaW51aiPhnPTI2/greentv.stream/index.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Eco & Cultural Shows",
    "currentShowBn": "পরিবেশ ও বিনোদন",
    "nextShow": "Next: Super Program Showcase (1:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (1:00 PM)",
    "viewers": 7844,
    "isPopular": false
  },
  {
    "id": "ch-37",
    "number": 37,
    "name": "Me Tv",
    "bnName": "মি টিভি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/9fq1Q4Hz/20240825_070144.png",
    "streamUrl": "https://iptvbd.live/metv1080/1080.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Music & Movies",
    "currentShowBn": "গান ও সিনেমা",
    "nextShow": "Next: Super Program Showcase (2:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (2:00 PM)",
    "viewers": 8023,
    "isPopular": false
  },
  {
    "id": "ch-38",
    "number": 38,
    "name": "SRK TV",
    "bnName": "এসআরকে টিভি",
    "category": "movies",
    "categoryLabel": "Movies",
    "categoryBn": "মুভি",
    "logo": "https://asset.bioscopelive.com/uploads/images/2025/08/11/thumbnails_58ebcef1efcc65837557de15952d2643_goplay_srk_tv_landscape.jpg",
    "streamUrl": "https://srknowapp.ncare.live/srktvhlswodrm/srktv.stream/playlist.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Superstar Movie Showcase",
    "currentShowBn": "সুপারস্টার মুভি শোকেস",
    "nextShow": "Next: Super Program Showcase (3:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (3:00 PM)",
    "viewers": 8202,
    "isPopular": false
  },
  {
    "id": "ch-39",
    "number": 39,
    "name": "Jago News 24",
    "bnName": "জাগো নিউজ ২৪",
    "category": "news",
    "categoryLabel": "News Channels",
    "categoryBn": "নিউজ চ্যানেল",
    "logo": "https://i.imgur.com/sqeIrMo.jpeg",
    "streamUrl": "https://app.ncare.live/live-orgin/jagonews24.stream/playlist.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Live News Feed",
    "currentShowBn": "লাইভ সংবাদ ফিড",
    "nextShow": "Next: Super Program Showcase (4:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (4:00 PM)",
    "viewers": 8381,
    "isPopular": false
  },
  {
    "id": "ch-40",
    "number": 40,
    "name": "Makkah Live",
    "bnName": "মক্কা লাইভ",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://www.jagobd.com/wp-content/uploads/2020/05/MakkahLive.jpg",
    "streamUrl": "https://app24.jagobd.com.bd/c3VydmVyX8RpbEU9Mi8xNy8yMFDEEHGcfRgzQ6NTAgdEoaeFzbF92YWxIZTO0U0ezN1IzMyfvcEdsEfeDeKiNkVN3PTOmdFseWRtaW51aiPhnPTI2/makkah.stream/index.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "SA",
    "language": "International",
    "currentShow": "Live Haram Sharif",
    "currentShowBn": "লাইভ হারাম শরীফ",
    "nextShow": "Next: Super Program Showcase (5:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (5:00 PM)",
    "viewers": 8560,
    "isPopular": true
  },
  {
    "id": "ch-41",
    "number": 41,
    "name": "Medina Live",
    "bnName": "মদিনা লাইভ",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://www.jagobd.com/wp-content/uploads/2020/05/Medina-Live.jpg",
    "streamUrl": "https://app24.jagobd.com.bd/c3VydmVyX8RpbEU9Mi8xNy8yMFDEEHGcfRgzQ6NTAgdEoaeFzbF92YWxIZTO0U0ezN1IzMyfvcEdsEfeDeKiNkVN3PTOmdFseWRtaW51aiPhnPTI2/madina.stream/index.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "SA",
    "language": "International",
    "currentShow": "Live Masjid an-Nabawi",
    "currentShowBn": "লাইভ মসজিদে নববী",
    "nextShow": "Next: Super Program Showcase (6:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (6:00 PM)",
    "viewers": 8739,
    "isPopular": true
  },
  {
    "id": "ch-42",
    "number": 42,
    "name": "Islamic TV",
    "bnName": "ইসলামিক টিভি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/J4nkLqHS/20260321_075216.png",
    "streamUrl": "https://app24.jagobd.com.bd/c3VydmVyX8RpbEU9Mi8xNy8yMFDEEHGcfRgzQ6NTAgdEoaeFzbF92YWxIZTO0U0ezN1IzMyfvcEdsEfeDeKiNkVN3PTOmdFseWRtaW51aiPhnPTI2/islamictvbd.stream/index.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Islamic Waz & Tilawat",
    "currentShowBn": "ইসলামিক ওয়াজ ও তিলাওয়াত",
    "nextShow": "Next: Super Program Showcase (7:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (7:00 PM)",
    "viewers": 8918,
    "isPopular": false
  },
  {
    "id": "ch-43",
    "number": 43,
    "name": "Peace TV Bangla",
    "bnName": "পিস টিভি বাংলা",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/vTYq396x/20250529-071345.png",
    "streamUrl": "https://dzkyvlfyge.erbvr.com/PeaceTvBangla/tracks-v3a1/mono.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "IN",
    "language": "Bangla",
    "currentShow": "Islamic Lectures",
    "currentShowBn": "ইসলামিক লেকচার ও প্রশ্নোত্তর",
    "nextShow": "Next: Super Program Showcase (8:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (8:00 PM)",
    "viewers": 9097,
    "isPopular": true
  },
  {
    "id": "ch-44",
    "number": 44,
    "name": "Iqra Bangla",
    "bnName": "ইকরা বাংলা",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/qqLNkFLg/20250531-104940.png",
    "streamUrl": "https://app.ncare.live/c3VydmVyX8RpbEU9Mi8xNy8yMDE0GIDU6RgzQ6NTAgdEoaeFzbF92YWxIZTO0U0ezN1IzMyfvcGVMZEJCTEFWeVN3PTOmdFsaWRtaW51aiPhnPTI2/iqrabanglatvoffice.stream/live-orgin/iqrabanglatvoffice.stream/chunks.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "SA",
    "language": "Bangla",
    "currentShow": "Quran & Hadith Study",
    "currentShowBn": "কুরআন ও হাদিস শিক্ষা",
    "nextShow": "Next: Super Program Showcase (9:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (9:00 PM)",
    "viewers": 9276,
    "isPopular": false
  },
  {
    "id": "ch-45",
    "number": 45,
    "name": "Quran TV",
    "bnName": "কুরআন টিভি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/T3f1NQyV/20260524-024937.png",
    "streamUrl": "https://live.kwikmotion.com/sharjahtvquranlive/shqurantv.smil/sharjahtvquranpublish/shqurantv_source/chunks.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "SA",
    "language": "International",
    "currentShow": "Live Quran Recitation",
    "currentShowBn": "লাইভ কুরআন তিলাওয়াত",
    "nextShow": "Next: Super Program Showcase (10:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (10:00 PM)",
    "viewers": 9455,
    "isPopular": false
  },
  {
    "id": "ch-46",
    "number": 46,
    "name": "Duronto TV",
    "bnName": "দুরন্ত টিভি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/0QRKCsfQ/20240823_020937.png",
    "streamUrl": "https://tvsen6.aynaott.com/6xyZ3N4oHv2KBJdB6W4p/index.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Kids Cartoons & Shows",
    "currentShowBn": "শিশুদের কার্টুন ও অনুষ্ঠান",
    "nextShow": "Next: Super Program Showcase (11:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (11:00 PM)",
    "viewers": 9634,
    "isPopular": true
  },
  {
    "id": "ch-47",
    "number": 47,
    "name": "Doraemon TV",
    "bnName": "ডোরেমন টিভি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://upload.wikimedia.org/wikipedia/en/b/bd/Doraemon_character.png",
    "streamUrl": "https://live20.bozztv.com/giatvplayout7/giatv-209902/tracks-v1a1/mono.ts.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "JP",
    "language": "Bangla",
    "currentShow": "Doraemon Adventures",
    "currentShowBn": "ডোরেমন ও নোবিতার কাণ্ডকারখানা",
    "nextShow": "Next: Super Program Showcase (12:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (12:00 PM)",
    "viewers": 9813,
    "isPopular": true
  },
  {
    "id": "ch-48",
    "number": 48,
    "name": "Tom & Jerry TV",
    "bnName": "টম অ্যান্ড জেরি টিভি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://image.tmdb.org/t/p/w500/pApniCXhegDnhxQda7RcpG8gFP0.jpg",
    "streamUrl": "https://live20.bozztv.com/giatvplayout7/giatv-208314/tracks-v1a1/mono.ts.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "US",
    "language": "English",
    "currentShow": "Classic Tom & Jerry",
    "currentShowBn": "মজার টম অ্যান্ড জেরি কার্টুন",
    "nextShow": "Next: Super Program Showcase (1:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (1:00 PM)",
    "viewers": 9992,
    "isPopular": false
  },
  {
    "id": "ch-49",
    "number": 49,
    "name": "Cartoon Network HD",
    "bnName": "কার্টুন নেটওয়ার্ক",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/k4mDbyJR/20240823_021424.png",
    "streamUrl": "https://stream.ottplus.bd/live/cn_hd_abr/live/cn_hd/chunks.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "IN",
    "language": "Hindi",
    "currentShow": "Ben 10 & Oggy",
    "currentShowBn": "বেন ১০ ও ওগি কার্টুন",
    "nextShow": "Next: Super Program Showcase (2:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (2:00 PM)",
    "viewers": 10171,
    "isPopular": true
  },
  {
    "id": "ch-50",
    "number": 50,
    "name": "Sony YaY",
    "bnName": "সনি ইয়ে",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/jSBDsbBX/20240823_021324.png",
    "streamUrl": "https://stream.ottplus.live/live/sony_yay_abr/live/sony_yay_720/chunks.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "IN",
    "language": "Hindi",
    "currentShow": "Kids Comedy Shows",
    "currentShowBn": "কিডস কমেডি শো",
    "nextShow": "Next: Super Program Showcase (3:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (3:00 PM)",
    "viewers": 10350,
    "isPopular": false
  },
  {
    "id": "ch-51",
    "number": 51,
    "name": "Star Jalsha HD",
    "bnName": "স্টার জলসা এইচডি",
    "category": "drama",
    "categoryLabel": "Natok & Drama",
    "categoryBn": "নাটক",
    "logo": "https://i.postimg.cc/0ykfppN3/20240822-231405.png",
    "streamUrl": "https://da86m1sqpm3o0.cloudfront.net/28072023/smil:starjalsha.smil/chunklist_b1928000.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "IN",
    "language": "Bangla",
    "currentShow": "Popular Mega Serials",
    "currentShowBn": "জনপ্রিয় মেগা সিরিয়াল",
    "nextShow": "Next: Super Program Showcase (4:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (4:00 PM)",
    "viewers": 10529,
    "isPopular": true
  },
  {
    "id": "ch-52",
    "number": 52,
    "name": "Zee Bangla HD",
    "bnName": "জি বাংলা এইচডি",
    "category": "drama",
    "categoryLabel": "Natok & Drama",
    "categoryBn": "নাটক",
    "logo": "https://i.postimg.cc/5tjSrbLS/20240822-231445.png",
    "streamUrl": "https://stream.ottplus.bd/live/zee_bangla_abr/live/zee_bangla_720/index.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "IN",
    "language": "Bangla",
    "currentShow": "Sa Re Ga Ma Pa & Serials",
    "currentShowBn": "সা রে গা মা পা ও সিরিয়াল",
    "nextShow": "Next: Super Program Showcase (5:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (5:00 PM)",
    "viewers": 10708,
    "isPopular": true
  },
  {
    "id": "ch-53",
    "number": 53,
    "name": "Colors Bangla HD",
    "bnName": "কালার্স বাংলা এইচডি",
    "category": "drama",
    "categoryLabel": "Natok & Drama",
    "categoryBn": "নাটক",
    "logo": "https://i.postimg.cc/3w6F5VZ5/20240822-231514.png",
    "streamUrl": "http://103.165.93.31:8095/colorsBangla/index.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "IN",
    "language": "Bangla",
    "currentShow": "Bengali Family Drama",
    "currentShowBn": "বাংলা পারিবারিক নাটক",
    "nextShow": "Next: Super Program Showcase (6:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (6:00 PM)",
    "viewers": 10887,
    "isPopular": true
  },
  {
    "id": "ch-54",
    "number": 54,
    "name": "Sony Aath",
    "bnName": "সনি আট",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/2yNd3WJ0/20240822-231606.png",
    "streamUrl": "https://stream.ottplus.live/live/sony_aath_abr/index.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "IN",
    "language": "Bangla",
    "currentShow": "CID & Detective Shows",
    "currentShowBn": "সিআইডি ও গোয়েন্দা গল্প",
    "nextShow": "Next: Super Program Showcase (7:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (7:00 PM)",
    "viewers": 11066,
    "isPopular": true
  },
  {
    "id": "ch-55",
    "number": 55,
    "name": "Sun Bangla",
    "bnName": "সান বাংলা",
    "category": "drama",
    "categoryLabel": "Natok & Drama",
    "categoryBn": "নাটক",
    "logo": "https://i.postimg.cc/y88mJsQC/20240823_020415.png",
    "streamUrl": "https://livestream7.sunnxt.com/bf76ee92dd01473bb2eb57d137294484/SunBanglaB_IN_index.mpd",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "IN",
    "language": "Bangla",
    "currentShow": "Sun Bangla Serials",
    "currentShowBn": "সান বাংলা মেগা সিরিয়াল",
    "nextShow": "Next: Super Program Showcase (8:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (8:00 PM)",
    "viewers": 11245,
    "isPopular": false
  },
  {
    "id": "ch-56",
    "number": 56,
    "name": "Jalsha Movies HD",
    "bnName": "জলসা মুভিজ এইচডি",
    "category": "movies",
    "categoryLabel": "Movies",
    "categoryBn": "মুভি",
    "logo": "https://i.postimg.cc/rFcCkS5m/20240822_231714.png",
    "streamUrl": "http://103.165.93.31:8095/jalshaMovies/tracks-v1a1/mono.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "IN",
    "language": "Bangla",
    "currentShow": "Tollywood Blockbuster",
    "currentShowBn": "টলিউড সুপারহিট সিনেমা",
    "nextShow": "Next: Super Program Showcase (9:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (9:00 PM)",
    "viewers": 11424,
    "isPopular": true
  },
  {
    "id": "ch-57",
    "number": 57,
    "name": "Zee Bangla Cinema",
    "bnName": "জি বাংলা সিনেমা",
    "category": "movies",
    "categoryLabel": "Movies",
    "categoryBn": "মুভি",
    "logo": "https://i.postimg.cc/dtBRtL99/20240822_231732.png",
    "streamUrl": "https://stream.ottplus.bd/live/zee_bangla_cinema_abr/index.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "IN",
    "language": "Bangla",
    "currentShow": "Non-stop Bangla Movies",
    "currentShowBn": "নন-স্টপ বাংলা সিনেমা",
    "nextShow": "Next: Super Program Showcase (10:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (10:00 PM)",
    "viewers": 11603,
    "isPopular": true
  },
  {
    "id": "ch-58",
    "number": 58,
    "name": "Colors HD",
    "bnName": "কালার্স এইচডি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/F1t6r1gv/20240823_023247.png",
    "streamUrl": "http://202.70.146.135:8000/play/a00b/index.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "IN",
    "language": "Hindi",
    "currentShow": "Bigg Boss & Reality Shows",
    "currentShowBn": "বিগ বস ও রিয়েলিটি শো",
    "nextShow": "Next: Super Program Showcase (11:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (11:00 PM)",
    "viewers": 11782,
    "isPopular": true
  },
  {
    "id": "ch-59",
    "number": 59,
    "name": "Star Plus HD",
    "bnName": "স্টার প্লাস এইচডি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/8k3QXzvt/20240823_022853.png",
    "streamUrl": "http://202.70.146.135:8000/play/a009/index.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "IN",
    "language": "Hindi",
    "currentShow": "Anupamaa & Hindi Serials",
    "currentShowBn": "অনুপমা ও জনপ্রিয় হিন্দি সিরিয়াল",
    "nextShow": "Next: Super Program Showcase (12:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (12:00 PM)",
    "viewers": 11961,
    "isPopular": true
  },
  {
    "id": "ch-60",
    "number": 60,
    "name": "Star Gold HD",
    "bnName": "স্টার গোল্ড এইচডি",
    "category": "movies",
    "categoryLabel": "Movies",
    "categoryBn": "মুভি",
    "logo": "https://i.postimg.cc/6pCXvxyz/20240823_022553.png",
    "streamUrl": "http://66.102.126.10:8000/play/a00f/index.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "IN",
    "language": "Hindi",
    "currentShow": "Bollywood Blockbuster Movies",
    "currentShowBn": "বলিউড ব্লকবাস্টার সিনেমা",
    "nextShow": "Next: Super Program Showcase (1:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (1:00 PM)",
    "viewers": 12140,
    "isPopular": true
  },
  {
    "id": "ch-61",
    "number": 61,
    "name": "Zee Tv",
    "bnName": "জি টিভি এইচডি",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/x8BwX6QW/20240823_022929.png",
    "streamUrl": "https://stream.ottplus.live/live/zee_tv_hd_abr/index.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "IN",
    "language": "Hindi",
    "currentShow": "Kumkum Bhagya & Serials",
    "currentShowBn": "কুমকুম ভাগ্য ও নাটক",
    "nextShow": "Next: Super Program Showcase (2:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (2:00 PM)",
    "viewers": 12319,
    "isPopular": true
  },
  {
    "id": "ch-62",
    "number": 62,
    "name": "Zee Cinema HD",
    "bnName": "জি সিনেমা এইচডি",
    "category": "movies",
    "categoryLabel": "Movies",
    "categoryBn": "মুভি",
    "logo": "https://i.postimg.cc/VN1c9Ztw/20240823_022636.png",
    "streamUrl": "https://stream.ottplus.live/live/zee_cinema_hd_abr/index.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "IN",
    "language": "Hindi",
    "currentShow": "Latest Bollywood Premieres",
    "currentShowBn": "সর্বশেষ বলিউড সিনেমার প্রিমিয়ার",
    "nextShow": "Next: Super Program Showcase (3:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (3:00 PM)",
    "viewers": 12498,
    "isPopular": true
  },
  {
    "id": "ch-63",
    "number": 63,
    "name": "Sony Max HD",
    "bnName": "সনি ম্যাক্স এইচডি",
    "category": "movies",
    "categoryLabel": "Movies",
    "categoryBn": "মুভি",
    "logo": "https://i.postimg.cc/YS3BdNNW/20240823_022655.png",
    "streamUrl": "https://stream.ottplus.bd/live/max_hd_abr/live/max_hd_720/chunks.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "IN",
    "language": "Hindi",
    "currentShow": "Blockbuster Action Movies",
    "currentShowBn": "ব্লকবাস্টার অ্যাকশন সিনেমা",
    "nextShow": "Next: Super Program Showcase (4:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (4:00 PM)",
    "viewers": 12677,
    "isPopular": true
  },
  {
    "id": "ch-64",
    "number": 64,
    "name": "Gold Mines",
    "bnName": "গোল্ড মাইনস",
    "category": "movies",
    "categoryLabel": "Movies",
    "categoryBn": "মুভি",
    "logo": "https://i.postimg.cc/7ZNqRywh/20240823-023440.png",
    "streamUrl": "https://cdn-2.pishow.tv/live/1459/master.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "IN",
    "language": "Hindi",
    "currentShow": "South Dubbed Blockbusters",
    "currentShowBn": "সাউথ ডাবিং সুপারহিট সিনেমা",
    "nextShow": "Next: Super Program Showcase (5:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (5:00 PM)",
    "viewers": 12856,
    "isPopular": true
  },
  {
    "id": "ch-65",
    "number": 65,
    "name": "Zee 24 Ghanta",
    "bnName": "জি ২৪ ঘণ্টা",
    "category": "news",
    "categoryLabel": "News Channels",
    "categoryBn": "নিউজ চ্যানেল",
    "logo": "https://i.postimg.cc/D0KSP0qB/Zee-24-Ghanta-2025-Logo-2025.webp",
    "streamUrl": "https://d2dsoyvkr33m05.cloudfront.net/index_5.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "IN",
    "language": "Bangla",
    "currentShow": "Kolkata News Live",
    "currentShowBn": "কলকাতা লাইভ নিউজ",
    "nextShow": "Next: Super Program Showcase (6:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (6:00 PM)",
    "viewers": 13035,
    "isPopular": false
  },
  {
    "id": "ch-66",
    "number": 66,
    "name": "Republic Bangla",
    "bnName": "রিপাবলিক বাংলা",
    "category": "news",
    "categoryLabel": "News Channels",
    "categoryBn": "নিউজ চ্যানেল",
    "logo": "https://i.postimg.cc/jdtWWWq3/Republic-bangla.webp",
    "streamUrl": "https://vg-republictvyupp.akamaized.net/ptnr-yuppt/v1/manifest/611d79b11b77e2f571934fd80ca1413453772ac7/vglive-sk-613605/93d674ab-f7a0-404e-88b2-b4f163373dbe/0.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "IN",
    "language": "Bangla",
    "currentShow": "Ghontay Ghontay Khabor",
    "currentShowBn": "ঘণ্টায় ঘণ্টায় খবর",
    "nextShow": "Next: Super Program Showcase (7:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (7:00 PM)",
    "viewers": 13214,
    "isPopular": true
  },
  {
    "id": "ch-67",
    "number": 67,
    "name": "TV9 Bangla",
    "bnName": "টিভি ৯ বাংলা",
    "category": "news",
    "categoryLabel": "News Channels",
    "categoryBn": "নিউজ চ্যানেল",
    "logo": "https://i.postimg.cc/85L5cGqH/Tv9bangla.webp",
    "streamUrl": "https://dyjmyiv3bp2ez.cloudfront.net/pub-iotv9banaen8yq/liveabr/playlist.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "IN",
    "language": "Bangla",
    "currentShow": "Non-stop News",
    "currentShowBn": "নন-স্টপ নিউজ আপডেট",
    "nextShow": "Next: Super Program Showcase (8:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (8:00 PM)",
    "viewers": 13393,
    "isPopular": false
  },
  {
    "id": "ch-68",
    "number": 68,
    "name": "Aaj Tak HD",
    "bnName": "আজ তক এইচডি",
    "category": "news",
    "categoryLabel": "News Channels",
    "categoryBn": "নিউজ চ্যানেল",
    "logo": "https://i.postimg.cc/ZnTTqdP5/Aaj-Tak-HD-v2.webp",
    "streamUrl": "https://aajtaklive-amd.akamaized.net/hls/live/2014416/aajtak/aajtaklive/live_720p/chunks.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "IN",
    "language": "Hindi",
    "currentShow": "Sabse Tez News",
    "currentShowBn": "সবসে তেজ খবর",
    "nextShow": "Next: Super Program Showcase (9:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (9:00 PM)",
    "viewers": 13572,
    "isPopular": false
  },
  {
    "id": "ch-69",
    "number": 69,
    "name": "Sangeet Bangla",
    "bnName": "সংগীত বাংলা",
    "category": "music",
    "categoryLabel": "Movie Songs",
    "categoryBn": "সিনেমার গান",
    "logo": "https://i.postimg.cc/pdddb1bs/20250529_120025.png",
    "streamUrl": "https://cdn-4.pishow.tv/live/1143/master.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "IN",
    "language": "Bangla",
    "currentShow": "Non-Stop Bangla Hits",
    "currentShowBn": "নন-স্টপ বাংলা রোমান্টিক গান",
    "nextShow": "Next: Super Program Showcase (10:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (10:00 PM)",
    "viewers": 13751,
    "isPopular": true
  },
  {
    "id": "ch-70",
    "number": 70,
    "name": "B4U Music",
    "bnName": "বিফোরইউ মিউজিক",
    "category": "music",
    "categoryLabel": "Movie Songs",
    "categoryBn": "সিনেমার গান",
    "logo": "https://i.postimg.cc/0N2VWksB/channels4-profile.jpg",
    "streamUrl": "https://stream.ottplus.bd/live/b4u_music_abr/index.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "IN",
    "language": "Hindi",
    "currentShow": "Bollywood Chartbusters",
    "currentShowBn": "বলিউড চার্টবাস্টার গান",
    "nextShow": "Next: Super Program Showcase (11:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (11:00 PM)",
    "viewers": 13930,
    "isPopular": false
  },
  {
    "id": "ch-71",
    "number": 71,
    "name": "9XM",
    "bnName": "৯এক্সএম",
    "category": "music",
    "categoryLabel": "Movie Songs",
    "categoryBn": "সিনেমার গান",
    "logo": "https://i.postimg.cc/SRKS6TwR/20240823_022008.png",
    "streamUrl": "https://wiselp.wiseplayout.com/9XM/master.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "IN",
    "language": "Hindi",
    "currentShow": "Bade Bhaiyya Beats",
    "currentShowBn": "নন-স্টপ হিন্দি হিট গান",
    "nextShow": "Next: Super Program Showcase (12:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (12:00 PM)",
    "viewers": 14109,
    "isPopular": false
  },
  {
    "id": "ch-72",
    "number": 72,
    "name": "Zoom",
    "bnName": "জুম টিভি",
    "category": "music",
    "categoryLabel": "Movie Songs",
    "categoryBn": "সিনেমার গান",
    "logo": "https://i.postimg.cc/7hz6tG8D/20250529_121941.png",
    "streamUrl": "https://pubads.g.doubleclick.net/ssai/event/JCAm25qkRXiKcK1AJMlvKQ/master.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "IN",
    "language": "Hindi",
    "currentShow": "Bollywood Gossips & Songs",
    "currentShowBn": "বলিউড গসিপ ও গান",
    "nextShow": "Next: Super Program Showcase (1:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (1:00 PM)",
    "viewers": 14288,
    "isPopular": false
  },
  {
    "id": "ch-73",
    "number": 73,
    "name": "T Sports",
    "bnName": "টি স্পোর্টস",
    "category": "sports",
    "categoryLabel": "Sports",
    "categoryBn": "স্পোর্টস",
    "logo": "https://i.postimg.cc/Qx3GZn6T/20240823_024117.png",
    "streamUrl": "https://tvsen5.aynaott.com/TnMn5kZz8aLm/index.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Live Cricket Match & Analysis",
    "currentShowBn": "লাইভ ক্রিকেট ম্যাচ ও বিশ্লেষণ",
    "nextShow": "Next: Super Program Showcase (2:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (2:00 PM)",
    "viewers": 14467,
    "isPopular": true
  },
  {
    "id": "ch-74",
    "number": 74,
    "name": "T Sports HD",
    "bnName": "টি স্পোর্টস এইচডি",
    "category": "sports",
    "categoryLabel": "Sports",
    "categoryBn": "স্পোর্টস",
    "logo": "https://i.postimg.cc/Qx3GZn6T/20240823_024117.png",
    "streamUrl": "https://tvsen5.aynaott.com/TnMn5kZz8aLm/index.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "BD",
    "language": "Bangla",
    "currentShow": "Live Bangladesh Premier League",
    "currentShowBn": "লাইভ বিপিএল ও আন্তর্জাতিক খেলা",
    "nextShow": "Next: Super Program Showcase (3:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (3:00 PM)",
    "viewers": 14646,
    "isPopular": true
  },
  {
    "id": "ch-75",
    "number": 75,
    "name": "A Sports HD",
    "bnName": "এ স্পোর্টস এইচডি",
    "category": "sports",
    "categoryLabel": "Sports",
    "categoryBn": "স্পোর্টস",
    "logo": "https://i.postimg.cc/W1z5BGPZ/20240823_024712.png",
    "streamUrl": "https://tvsen6.aynaott.com/zv68oqPDu7MZZwmHhRxt/tracks-v1a1/mono.ts.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "PK",
    "language": "International",
    "currentShow": "Live Cricket & Football",
    "currentShowBn": "লাইভ ক্রিকেট ও ফুটবল টুর্নামেন্ট",
    "nextShow": "Next: Super Program Showcase (4:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (4:00 PM)",
    "viewers": 14825,
    "isPopular": true
  },
  {
    "id": "ch-76",
    "number": 76,
    "name": "Willow Sports",
    "bnName": "উইলো স্পোর্টস",
    "category": "sports",
    "categoryLabel": "Sports",
    "categoryBn": "স্পোর্টস",
    "logo": "https://i.postimg.cc/HntSg3xw/20240823_024624.png",
    "streamUrl": "https://tvsen5.aynaott.com/willowhd/index.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "US",
    "language": "English",
    "currentShow": "Live International Cricket",
    "currentShowBn": "লাইভ আন্তর্জাতিক ক্রিকেট",
    "nextShow": "Next: Super Program Showcase (5:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (5:00 PM)",
    "viewers": 15004,
    "isPopular": true
  },
  {
    "id": "ch-77",
    "number": 77,
    "name": "Euro Sports HD",
    "bnName": "ইউরো স্পোর্টস এইচডি",
    "category": "sports",
    "categoryLabel": "Sports",
    "categoryBn": "স্পোর্টস",
    "logo": "https://i.postimg.cc/pXx765TQ/20240823_024350.png",
    "streamUrl": "https://stream.ottplus.bd/live/euro_sports_hd_abr/index.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "EU",
    "language": "English",
    "currentShow": "Cycling & Grand Slam",
    "currentShowBn": "সাইক্লিং ও গ্র্যান্ড স্ল্যাম টেনিস",
    "nextShow": "Next: Super Program Showcase (6:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (6:00 PM)",
    "viewers": 15183,
    "isPopular": false
  },
  {
    "id": "ch-78",
    "number": 78,
    "name": "Star Sports 1",
    "bnName": "স্টার স্পোর্টস ১",
    "category": "sports",
    "categoryLabel": "Sports",
    "categoryBn": "স্পোর্টস",
    "logo": "https://i.postimg.cc/DzDHjCJm/20240823_024249.png",
    "streamUrl": "https://flussonic.defineatoz.com/Starsports1/tracks-v1a1/mono.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "IN",
    "language": "English",
    "currentShow": "Live World Cricket",
    "currentShowBn": "লাইভ বিশ্বকাপ ক্রিকেট",
    "nextShow": "Next: Super Program Showcase (7:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (7:00 PM)",
    "viewers": 15362,
    "isPopular": true
  },
  {
    "id": "ch-79",
    "number": 79,
    "name": "Star Sports 2",
    "bnName": "স্টার স্পোর্টস ২",
    "category": "sports",
    "categoryLabel": "Sports",
    "categoryBn": "স্পোর্টস",
    "logo": "https://i.postimg.cc/zBgM9nK7/20240823_024306.png",
    "streamUrl": "https://tvsen7.aynaott.com/ssport2hd/index.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "IN",
    "language": "English",
    "currentShow": "Football & Kabaddi Live",
    "currentShowBn": "ফুটবল ও কাবাডি লাইভ",
    "nextShow": "Next: Super Program Showcase (8:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (8:00 PM)",
    "viewers": 15541,
    "isPopular": false
  },
  {
    "id": "ch-80",
    "number": 80,
    "name": "Sony Ten 1",
    "bnName": "সনি টেন ১",
    "category": "sports",
    "categoryLabel": "Sports",
    "categoryBn": "স্পোর্টস",
    "logo": "https://i.postimg.cc/65fsWLS1/20240823_024136.png",
    "streamUrl": "https://stream.ottplus.live/live/ten_1_hd_abr/live/ten_1_hd_720/index.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "IN",
    "language": "English",
    "currentShow": "WWE Raw & SmackDown",
    "currentShowBn": "ডাব্লুডাব্লুই র ও স্ম্যাকডাউন",
    "nextShow": "Next: Super Program Showcase (9:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (9:00 PM)",
    "viewers": 15720,
    "isPopular": true
  },
  {
    "id": "ch-81",
    "number": 81,
    "name": "Sony Ten 2",
    "bnName": "সনি টেন ২",
    "category": "sports",
    "categoryLabel": "Sports",
    "categoryBn": "স্পোর্টস",
    "logo": "https://i.postimg.cc/wjqC7RYx/20240823_024150.png",
    "streamUrl": "https://stream.ottplus.live/live/ten_2_hd_abr/live/ten_2_hd_720/index.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "IN",
    "language": "English",
    "currentShow": "UEFA Champions League",
    "currentShowBn": "উয়েফা চ্যাম্পিয়ন্স লিগ ফুটবল",
    "nextShow": "Next: Super Program Showcase (10:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (10:00 PM)",
    "viewers": 15899,
    "isPopular": false
  },
  {
    "id": "ch-82",
    "number": 82,
    "name": "Sony Ten 5",
    "bnName": "সনি টেন ৫",
    "category": "sports",
    "categoryLabel": "Sports",
    "categoryBn": "স্পোর্টস",
    "logo": "https://i.postimg.cc/W4tx7R4Q/20240823_024232.png",
    "streamUrl": "https://stream.ottplus.live/live/ten_5_hd_abr/live/ten_5_hd_720/index.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "IN",
    "language": "English",
    "currentShow": "Live Sports Action",
    "currentShowBn": "লাইভ স্পোর্টস অ্যাকশন",
    "nextShow": "Next: Super Program Showcase (11:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (11:00 PM)",
    "viewers": 16078,
    "isPopular": true
  },
  {
    "id": "ch-83",
    "number": 83,
    "name": "Bein Sports 1",
    "bnName": "বিইন স্পোর্টস ১",
    "category": "sports",
    "categoryLabel": "Sports",
    "categoryBn": "স্পোর্টস",
    "logo": "https://i.postimg.cc/441hHtgZ/20250120_193746.png",
    "streamUrl": "http://host.phorious.art/validation/377?deviceMac=10:27:BE:25:67:80&split=33da9c80155413830543e27c8520ba99&smart=1",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "QA",
    "language": "English",
    "currentShow": "Premier League Live",
    "currentShowBn": "প্রিমিয়ার লিগ ফুটবল লাইভ",
    "nextShow": "Next: Super Program Showcase (12:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (12:00 PM)",
    "viewers": 16257,
    "isPopular": true
  },
  {
    "id": "ch-84",
    "number": 84,
    "name": "Gold Mines Bollywood",
    "bnName": "গোল্ড মাইনস বলিউড",
    "category": "movies",
    "categoryLabel": "Movies",
    "categoryBn": "মুভি",
    "logo": "https://i.postimg.cc/7ZNqRywh/20240823-023440.png",
    "streamUrl": "https://mumt03.tangotv.in/Dsly5z3HGOLDMINESBOLLYWOOD/index.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "IN",
    "language": "Hindi",
    "currentShow": "Blockbuster Movies",
    "currentShowBn": "ব্লকবাস্টার হিন্দি সিনেমা",
    "nextShow": "Next: Super Program Showcase (1:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (1:00 PM)",
    "viewers": 16436,
    "isPopular": false
  },
  {
    "id": "ch-85",
    "number": 85,
    "name": "ZB Cinema",
    "bnName": "জেডবি সিনেমা",
    "category": "movies",
    "categoryLabel": "Movies",
    "categoryBn": "মুভি",
    "logo": "https://i.postimg.cc/L8xzTtQY/k-Ug6WSk.jpg",
    "streamUrl": "https://server.zillarbarta.com/ZBCINEMA/index.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "IN",
    "language": "Hindi",
    "currentShow": "Action & Romance Movies",
    "currentShowBn": "অ্যাকশন ও রোমান্টিক সিনেমা",
    "nextShow": "Next: Super Program Showcase (2:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (2:00 PM)",
    "viewers": 16615,
    "isPopular": false
  },
  {
    "id": "ch-86",
    "number": 86,
    "name": "Animal Planet HD",
    "bnName": "অ্যানিমেল প্ল্যানেট",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/43NXkFx5/20240823_023458.png",
    "streamUrl": "https://tiger-hub.vercel.app@vodzong.mjunoon.tv:8087/streamtest/Animal-Planet-158-3/playlist.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "US",
    "language": "English",
    "currentShow": "Wildlife Safari",
    "currentShowBn": "বন্যপ্রাণী ও সাফারি",
    "nextShow": "Next: Super Program Showcase (3:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (3:00 PM)",
    "viewers": 16794,
    "isPopular": true
  },
  {
    "id": "ch-87",
    "number": 87,
    "name": "Discovery",
    "bnName": "ডিসকভারি চ্যানেল",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/cJ90sMKN/20240823_023541.png",
    "streamUrl": "http://202.70.146.135:8000/play/a05z/index.m3u8",
    "streamType": "hls",
    "resolution": "4K",
    "country": "US",
    "language": "English",
    "currentShow": "Man vs Wild & Science",
    "currentShowBn": "বিজ্ঞান ও রোমাঞ্চকর আবিষ্কার",
    "nextShow": "Next: Super Program Showcase (4:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (4:00 PM)",
    "viewers": 16973,
    "isPopular": true
  },
  {
    "id": "ch-88",
    "number": 88,
    "name": "National Geographic HD",
    "bnName": "ন্যাশনাল জিওগ্রাফিক",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/VN6PHrKZ/20240823_023950.png",
    "streamUrl": "https://tvsen3.aynaott.com/7mm4pwCy/index.m3u8",
    "streamType": "hls",
    "resolution": "1080p FHD",
    "country": "US",
    "language": "English",
    "currentShow": "Mysteries of the Universe",
    "currentShowBn": "মহাবিশ্বের রহস্য ও প্রকৃতি",
    "nextShow": "Next: Super Program Showcase (5:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (5:00 PM)",
    "viewers": 17152,
    "isPopular": true
  },
  {
    "id": "ch-89",
    "number": 89,
    "name": "Sony BBC Earth",
    "bnName": "সনি বিবিসি আর্থ",
    "category": "entertainment",
    "categoryLabel": "General TV",
    "categoryBn": "সাধারণ টিভি",
    "logo": "https://i.postimg.cc/MZR248Yw/20240823_024104.png",
    "streamUrl": "https://amg00793-amg00793c6-xumo-us-2669.playouts.now.amagi.tv/BBCStudios-BBCEarthA-hls/playlist540p.m3u8",
    "streamType": "hls",
    "resolution": "720p HD",
    "country": "GB",
    "language": "English",
    "currentShow": "Planet Earth Wonders",
    "currentShowBn": "পৃথিবীর অপরূপ প্রকৃতি",
    "nextShow": "Next: Super Program Showcase (6:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (6:00 PM)",
    "viewers": 17331,
    "isPopular": false
  },
  {
    "id": "ch-90",
    "number": 90,
    "name": "Alpha (2026)",
    "bnName": "আলফা (২০২৬ মুভি)",
    "category": "movies",
    "categoryLabel": "Movies",
    "categoryBn": "মুভি",
    "logo": "https://image.tmdb.org/t/p/w600_and_h900_bestv2/nuLMioRauQacj4bRXRsJX9Oe5H6.jpg",
    "streamUrl": "https://pub-4e135af7e68844d8816cb0f642379557.r2.dev/CINEFREAK.TOP%20-%20Alpha%20%282026%29%20DS4K%20WEB-DL%20%5BHindi%5D%20720p%20HEVC%20ESub.mkv",
    "streamType": "video",
    "resolution": "4K",
    "country": "US",
    "language": "Hindi",
    "currentShow": "Latest Cinefreak 4K Release",
    "currentShowBn": "সর্বশেষ রিলিজ হওয়া ব্লকবাস্টার মুভি",
    "nextShow": "Next: Super Program Showcase (7:00 PM)",
    "nextShowBn": "পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (7:00 PM)",
    "viewers": 17510,
    "isPopular": true
  }
];

// Add channels 91 to 200 from the sequence
const categorySeq = [
  { cat: "sports", catLabel: "Sports", catBn: "স্পোর্টস", country: "BD", lang: "English", res: "1080p FHD" },
  { cat: "movies", catLabel: "Movies", catBn: "মুভি", country: "IN", lang: "Hindi", res: "720p HD" },
  { cat: "drama", catLabel: "Natok & Drama", catBn: "নাটক", country: "BD", lang: "Bangla", res: "4K" },
  { cat: "music", catLabel: "Movie Songs", catBn: "সিনেমার গান", country: "IN", lang: "English", res: "1080p FHD" },
  { cat: "news", catLabel: "News Channels", catBn: "নিউজ চ্যানেল", country: "BD", lang: "Bangla", res: "720p HD" },
  { cat: "entertainment", catLabel: "General TV", catBn: "সাধারণ টিভি", country: "IN", lang: "Hindi", res: "4K" }
];

const timeSlots = ["8:00 PM", "9:00 PM", "10:00 PM", "11:00 PM", "12:00 PM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM", "5:00 PM", "6:00 PM", "7:00 PM"];

for (let num = 91; num <= 200; num++) {
  const seqIdx = (num - 91) % categorySeq.length;
  const timeIdx = (num - 91) % timeSlots.length;
  const seq = categorySeq[seqIdx];
  const time = timeSlots[timeIdx];
  const viewers = 17689 + ((num - 91) * 179) % 20000;

  rawChannels.push({
    id: `ch-${num}`,
    number: num,
    name: `Habil Global Channel ${num}`,
    bnName: `হাবিল গ্লোবাল চ্যানেল ${num}`,
    category: seq.cat,
    categoryLabel: seq.catLabel,
    categoryBn: seq.catBn,
    logo: `https://api.dicebear.com/7.x/initials/svg?seed=Habil%20Global%20Channel%20${num}&backgroundColor=0f172a&textColor=f43f5e&fontSize=38&chars=2`,
    streamUrl: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    streamType: "hls",
    resolution: seq.res,
    country: seq.country,
    language: seq.lang,
    currentShow: `Live Stream & HD Broadcast #${num}`,
    currentShowBn: `লাইভ স্ট্রিম ও এইচডি সম্প্রচার #${num}`,
    nextShow: `Next: Super Program Showcase (${time})`,
    nextShowBn: `পরবর্তী: জনপ্রিয় মেগা অনুষ্ঠান (${time})`,
    viewers: viewers,
    isPopular: false
  });
}

// Convert to full application schema
const fullChannels = rawChannels.map((c) => {
  const countryFull = c.country === 'BD' ? 'Bangladesh' :
    c.country === 'IN' ? 'India' :
    c.country === 'SA' ? 'Saudi Arabia' :
    c.country === 'US' ? 'USA' :
    c.country === 'JP' ? 'Japan' :
    c.country === 'PK' ? 'Pakistan' :
    c.country === 'QA' ? 'Qatar' :
    c.country === 'GB' ? 'UK' :
    c.country === 'EU' ? 'Europe' : c.country;

  const quality = c.resolution === '4K' ? '4K' :
    c.resolution === '1080p FHD' ? 'Full HD' :
    c.resolution === '720p HD' ? 'HD' : 'Full HD';

  const catUpper = (c.category || 'ENTERTAINMENT').toUpperCase();

  return {
    id: c.id,
    channelNumber: c.number,
    name: c.name,
    bnName: c.bnName,
    logo: c.logo,
    category: catUpper,
    categoryLabel: c.categoryLabel,
    categoryBn: c.categoryBn,
    streamUrl: c.streamUrl,
    backupStreamUrl: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    streamType: c.streamType || 'hls',
    resolution: c.resolution || '1080p FHD',
    description: `${c.name} (${c.bnName || ''}) - ${c.currentShow || 'Live Broadcast'}. High-speed low-latency stream.`,
    country: countryFull,
    language: c.language || 'Bangla',
    quality: quality,
    status: 'online',
    isFeatured: Boolean(c.isPopular || c.number <= 16),
    isPopular: Boolean(c.isPopular),
    sortOrder: c.number,
    enabled: true,
    viewCount: (c.viewers || 1000) * 12,
    viewers: c.viewers || 1500,
    currentShow: c.currentShow,
    currentShowBn: c.currentShowBn,
    nextShow: c.nextShow,
    nextShowBn: c.nextShowBn,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  };
});

console.log(`Generated ${fullChannels.length} total channels!`);

// Write channels.json in root and src/data/channels.json
const rootChannelsPath = path.join(__dirname, '..', 'channels.json');
const srcChannelsPath = path.join(__dirname, '..', 'src', 'data', 'channels.json');

fs.writeFileSync(rootChannelsPath, JSON.stringify(fullChannels, null, 2), 'utf-8');
fs.writeFileSync(srcChannelsPath, JSON.stringify(fullChannels, null, 2), 'utf-8');
console.log(`Saved channels.json to root and src/data/ successfully!`);

// Also update db.json
const dbPath = path.join(__dirname, '..', 'db.json');
let existingDb = {};
if (fs.existsSync(dbPath)) {
  try {
    existingDb = JSON.parse(fs.readFileSync(dbPath, 'utf-8'));
  } catch (e) {}
}

existingDb.channels = fullChannels;
existingDb.lastSyncTime = Date.now();
fs.writeFileSync(dbPath, JSON.stringify(existingDb, null, 2), 'utf-8');
console.log(`Updated db.json with ${fullChannels.length} channels successfully!`);
